In [1]:
import numpy as np

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("Shape of A:", A.shape)

print("\nMatrix B:\n", B)
print("Shape of B:", B.shape)

elementwise = A * B
print("\nElement-wise Multiplication:\n", elementwise)

matrix_mult = np.dot(A, B)
print("\nMatrix Multiplication:\n", matrix_mult)

det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

inv_A = np.linalg.inv(A)
print("\nInverse of A:\n", inv_A)

arr = np.random.randint(1, 20, 5)
print("\nOriginal 1D Array:", arr)

normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print("Normalized Array:", normalized)

C = np.random.randint(1, 10, (4, 3))
print("\nMatrix C:\n", C)

col_mean = np.mean(C, axis=0)
print("Column Means:", col_mean)

broadcasted = C - col_mean
print("\nAfter Broadcasting (Column Mean Subtracted):\n", broadcasted)

Matrix A:
 [[6 1 1]
 [7 4 1]
 [8 7 1]]
Shape of A: (3, 3)

Matrix B:
 [[2 9 2]
 [3 6 5]
 [4 3 1]]
Shape of B: (3, 3)

Element-wise Multiplication:
 [[12  9  2]
 [21 24  5]
 [32 21  1]]

Matrix Multiplication:
 [[ 19  63  18]
 [ 30  90  35]
 [ 41 117  52]]

Determinant of A: 0.0


LinAlgError: Singular matrix